################################################################################
# ################################################################################  
# #                                                                              #  
# # Viterbi HDL Code Generator                                                   #  
# # Copyright (C) 2004  Sheng Zhu                                                #  
# #                                                                              #  
# # This program is free software; you can redistribute it and/or                #  
# # modify it under the terms of the GNU General Public License                  #  
# # as published by the Free Software Foundation; either version 2               #  
# # of the License, or (at your option) any later version.                       #  
# #                                                                              #  
# # This program is distributed in the hope that it will be useful,              #  
# # but WITHOUT ANY WARRANTY; without even the implied warranty of               #  
# # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #  
# # GNU General Public License for more details.                                 #  
# #                                                                              #  
# # You should have received a copy of the GNU General Public License            #  
# # along with this program; if not, write to the Free Software                  #  
# # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.  #  
# #                                                                              #  
# # If you have any problem, please email to me: jhonson.zhu@gmail.com           #  
# #                                                                              #  
# ################################################################################
################################################################################
# Version 1.2 based on version 1.1, Update date: 2008/12/18
#             include adjustment by moti.
#             change the file name, just like from trabacknew2.v to traceback.v
#             change the directory of verilog files from "module" to "rtl/verilog"
#             add encoder.pl, for generating encoder.v. 
#             Note: encode.pl is for c program
#             move testbench.v to "bench/verilog"
#             two testbench
#             add global valuables $script_dir, the full path to perl files
#                 for example, c:/morpheus1.2/perl
# Version 1.1 Updated date: 2006/7
#/usr/bin/perl -w

if($#ARGV>=1){
#	print @ARGV, "\n";
	%argv=@ARGV;
#	print $argv{'-POLYS'}, "\n";
}
else {die "no arguments input\nusage: command -POLYS \"91 121 101 91\" -B 1 -V 1 -SYNCRAM 1 -RAW 10 -OSR 4 -DBN 2\n
      or command -POLYS \"91 121 101 91\" -B 1 -V 1 -SYNCRAM 1 -DIRECTTB 1 -RAW 10 -TB_LEN 128 -TB_OUT 64\n";}

$home_dir=exists($argv{'-HOMEDIR'})?$argv{'-HOMEDIR'}:".";
$script_dir= exists($argv{'-SCRIPTDIR'})?"$home_dir/$argv{'-SCRIPTDIR'}":"$home_dir/perl"; 
$DIRECTTB = exists($argv{'-DIRECTTB'})?$argv{'-DIRECTTB'}:0;
require "$script_dir/morphs.pl";
require "$script_dir/utility.pl";
require "$script_dir/glb_def.pl";
require "$script_dir/pe.pl";
require "$script_dir/smu.pl";
require "$script_dir/virtual_mem.pl";
require "$script_dir/vit.pl";
require "$script_dir/ctrl.pl";
require "$script_dir/decoder.pl";
require "$script_dir/encoder.pl";
require "$script_dir/testbench.pl";
require "$script_dir/encode.pl";
require "$script_dir/vit2cpp.pl";
if($DIRECTTB){
    require "$script_dir/centrofilo.pl";
    require "$script_dir/dirtraback.pl";
    require "$script_dir/tbdir_mod.pl";} 
else {
    require "$script_dir/filo.pl";
    require "$script_dir/traceback.pl";};

# initial home directory
readIni();

$LICENSE = 
'///////////////////////////////////////////////////////////////////
         //////                                    //////
///////////////////////////////////////////////////////////////////
///                                                             ///
/// This file is generated by Viterbi HDL Code Generator(VHCG)  ///
/// which is written by Mike Johnson at OpenCores.org  and      ///
/// distributed under GPL license.                              ///
///                                                             ///
/// If you have any advice,                                     ///
/// please email to jhonson.zhu@gmail.com                       ///
///                                                             ///
///////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////


';
$VERSION = "1.3";

print "OK";
para_initial();
butfly2(\$mod_name, \@ports_names);
delayT(\$mod_name, \@ports_names);
def_initial();
print "B=",$B,", $para_symbol_num, $W, $V, $U  @para_polys\n";
genfile("glb_def.v", \&glb_def);
genfile("ctrl.v", \&ctrl);

($DIRECTTB==1)?genfile("centrofilo.v", \&centrofilo):genfile("filo.v", \&filo);
($DIRECTTB==1)?genfile("dirtraback.v", \&dirtraback):genfile("traceback.v", \&traceback);
($DIRECTTB==1)?genfile("decoder.v", \&direct_tb_decoder):genfile("decoder.v", \&decoder);
($DIRECTTB==1)?genfile("tbdir_mod.v", \&tbdir_mod):0;
($DIRECTTB==1)?genfile("../../bench/verilog/test_random_data.v", \&test_random_data_tbdir):
          genfile("../../bench/verilog/test_random_data.v", \&test_random_data);

genfile("pe.v", \&pe);
genfile("smu.v", \&smu);
genfile("virtual_mem.v", \&virtual_mem);
genfile("vit.v", \&vit);
genfile("encoder.v", \&encoder);
genfile("../../bench/verilog/test_fix_data.v", \&test_fix_data);
genfile("../../c/encode.cpp", \&encode);
genfile("../../c/vit.cpp", \&vit2cpp);
genFile("../../sim/icarus/block.list", \&block_list);
genFile("../../sim/modelsim/do.txt", \&do_txt);
genFile("../../sim/icarus/compile.bat", \&compile_bat);
genFile("../../sim/icarus/gtk.bat", \&gtk_bat);
genFile("../../sim/icarus/run_fix_data.bat", \&run_fix_data_bat);
genFile("../../sim/icarus/run_random_data.bat", \&run_random_data_bat);
genFile("../../sim/icarus/self_test.bat", \&self_test_bat);
print "1";		## tell outside it is ok
1
